### ISSUE TITLE
Another when trying to startup the bot

### ISSUE THREAD

**Issue by Dunkstormen** [Starfox64/FoxedBot#14]
I got this error when trying to start the bot 

C:\Users\Administrator\Desktop\SteamBot\Bot\Bot\foxedbot.js>node app.js
Loading FoxedBot...
Logged in as empiregamingbot!
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at Server.listen (net.js:1240:5)
    at SteamClient.<anonymous> (C:\Users\Administrator\Desktop\SteamBot\Bot\Bot\
foxedbot.js\app.js:88:9)
    at SteamClient.emit (events.js:104:17)
    at SteamClient.handlers.(anonymous function) (C:\Users\Administrator\Desktop
\SteamBot\Bot\Bot\foxedbot.js\node_modules\steam\lib\handlers\user.js:163:10)
    at SteamClient._netMsgReceived (C:\Users\Administrator\Desktop\SteamBot\Bot\
Bot\foxedbot.js\node_modules\steam\lib\steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (C:\Users\Administrator\Desktop
\SteamBot\Bot\Bot\foxedbot.js\node_modules\steam\lib\steam_client.js:192:10)
    at SteamClient._netMsgReceived (C:\Users\Administrator\Desktop\SteamBot\Bot\
Bot\foxedbot.js\node_modules\steam\lib\steam_client.js:106:26)

**Comment by Starfox64** [comment]
Make sure that only one instance of the bot is running. If not this means that another process is using the port the bot is trying to listen on.

**Comment by Dunkstormen** [comment]
Well it seems that i only get this error after i try running "forever start app.js" in the bots directory

**Comment by Starfox64** [comment]
Do you mean that you are running node app.js then forever start app.js?
