### ISSUE TITLE
Foxedbot error

### ISSUE THREAD

**Issue by ghost** [Starfox64/FoxedBot#19]
I get a error when running the foxedbot:

```
root@185:/bots# nodejs app.js
Loading FoxedBot...

/bots/node_modules/steam/lib/steam_client.js:150
  var cryptedSessKey = require('crypto').publicEncrypt(fs.readFileSync(__dirna
                                         ^
TypeError: Object #<Object> has no method 'publicEncrypt'
    at SteamClient.handlers.(anonymous function) (/bots/node_modules/steam/lib/steam_client.js:150:42)
    at SteamClient._netMsgReceived (/bots/node_modules/steam/lib/steam_client.js:106:26)
    at Connection.EventEmitter.emit (events.js:95:17)
    at Connection._readPacket (/bots/node_modules/steam/lib/connection.js:50:8)
    at Connection.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Connection.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)

```

**Comment by ghost** [comment]
Solved, was because I used the "nodejs" package from apt-get.
