### ISSUE TITLE
ServerID's

### ISSUE THREAD

**Issue by NotSoSuper** [Starfox64/FoxedBot#2]
/root/node_modules/foxedbot.js/config/commands.js:98
                if (!isNaN(args[i]) && id >= 0 && servers[id]) {
                                                  ^
ReferenceError: servers is not defined
    at Object.func (/root/node_modules/foxedbot.js/config/commands.js:98:37)
    at SteamClient.<anonymous> (/root/node_modules/foxedbot.js/app.js:107:30)
    at SteamClient.emit (events.js:118:17)
    at SteamClient.handlers.(anonymous function) (/root/node_modules/foxedbot.js/node_modules/steam/lib/handlers/friends.js:211:8)
    at SteamClient._netMsgReceived (/root/node_modules/foxedbot.js/node_modules/steam/lib/steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (/root/node_modules/foxedbot.js/node_modules/steam/lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/root/node_modules/foxedbot.js/node_modules/steam/lib/steam_client.js:106:26)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/root/node_modules/foxedbot.js/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:104:17)

Config Screenshots: http://gyazo.com/497b4f36023e1708e335b00725582dbb
http://gyazo.com/4082221bb3de2639b397db40cd0196b1

**Comment by NotSoSuper** [comment]
The bot crashes when I type !select 1

**Comment by Starfox64** [comment]
Working on it, it's an issue due to the big update I've talked about.

Also, the first ServerID is 0 so if your ServerID is 1 this means that it's your seconds server.
_Just warning you._

**Comment by NotSoSuper** [comment]
Thanks.

**Comment by Starfox64** [comment]
**Fixed**
_Fixed commands.js_
_Added SteamGuard_
