### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by kotone123** [Starfox64/FoxedBot#20]
/root/foxedbot.js/app.js:188
                                if (message.toLowerCase().startsWith(command.toLowerCase())) {
                                                          ^
TypeError: undefined is not a function
    at SteamClient.<anonymous> (/root/foxedbot.js/app.js:188:31)
    at SteamClient.emit (events.js:118:17)
    at SteamClient.handlers.(anonymous function) (/root/node_modules/steam/lib/handlers/friends.js:251:8)
    at SteamClient._netMsgReceived (/root/node_modules/steam/lib/steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (/root/node_modules/steam/lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/root/node_modules/steam/lib/steam_client.js:106:26)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/root/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)

**Comment by Starfox64** [comment]
Are you able to tell me what command was typed or are able to reproduce it?

**Comment by kotone123** [comment]
!help or any ! command

**Comment by Starfox64** [comment]
Can you enable _logChat_ and show me the output of the log file.

**Comment by kotone123** [comment]
[2015-10-11 20:20:58.324] [INFO] LOG - Kotone: !help
/root/foxedbot.js/app.js:188
                                if (message.toLowerCase().startsWith(command.toLowerCase())) {
                                                          ^
TypeError: undefined is not a function
    at SteamClient.<anonymous> (/root/foxedbot.js/app.js:188:31)
    at SteamClient.emit (events.js:118:17)
    at SteamClient.handlers.(anonymous function) (/root/node_modules/steam/lib/handlers/friends.js:251:8)
    at SteamClient._netMsgReceived (/root/node_modules/steam/lib/steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (/root/node_modules/steam/lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/root/node_modules/steam/lib/steam_client.js:106:26)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/root/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
root@vps:~/foxedbot.js#

**Comment by kotone123** [comment]
where would the log file be located?

**Comment by Starfox64** [comment]
In the **log** folder inside the **foxedbot.js** folder.

**Comment by kotone123** [comment]
[2015-10-11 20:20:42.598] [INFO] LOG - Sentry hash found, reading...
[2015-10-11 20:20:51.100] [INFO] LOG - Logged in as profscoots1337!
[2015-10-11 20:20:51.109] [INFO] LOG - FoxedBot is now listening on port 25000.
[2015-10-11 20:20:58.324] [INFO] LOG - Kotone: !help
is all whats in the log folder

**Comment by Starfox64** [comment]
Did you upgrade from an older version or is this a fresh install?
Could you also show me your node.js version (node --version)

**Comment by kotone123** [comment]
root@vps:~/foxedbot.js# node --version
v0.12.7

**Comment by Starfox64** [comment]
Are you using the latest version of FoxedBot? The **!** prefix was remove in the current version.

**Comment by kotone123** [comment]
im using the most recent version

**Comment by Starfox64** [comment]
This issue seems to be cause by this version of node.js (Was able to reproduce using v0.12.7) please download the latest node.js version **v4.1.2**.

I will be updating the documentation.

**Comment by kotone123** [comment]
how would i do that?

**Comment by Starfox64** [comment]
I suggest using **nvm**, a node module that lets you install pretty much any version of node.js.

**Comment by kotone123** [comment]
do i install node js v4.12 or steam 4.12?

**Comment by Starfox64** [comment]
node.js
