### ISSUE TITLE
Error upon launching:

### ISSUE THREAD

**Issue by Phoenixf129** [Starfox64/FoxedBot#5]
/home/foxedbot.js/node_modules/steam/lib/steam_client.js:150
  var cryptedSessKey = require('crypto').publicEncrypt(fs.readFileSync(__dirna
                                         ^
TypeError: Object #<Object> has no method 'publicEncrypt'
    at SteamClient.handlers.(anonymous function) (/home/foxedbot.js/node_modules/steam/lib/steam_client.js:150:42)
    at SteamClient._netMsgReceived (/home/foxedbot.js/node_modules/steam/lib/steam_client.js:106:26)
    at Connection.emit (events.js:95:17)
    at Connection._readPacket (/home/foxedbot.js/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Connection.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)

**Comment by Phoenixf129** [comment]
Turns out nvm was being awkward, and refused to use 0.12.0, instead using the older versions.
